--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4
-- Dumped by pg_dump version 15.5 (Debian 15.5-0+deb12u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: liquibase
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO liquibase;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: liquibase
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO liquibase;

--
-- Name: wf_master; Type: TABLE; Schema: public; Owner: liquibase
--

CREATE TABLE public.wf_master (
    wf_def_id integer NOT NULL,
    wf_name character varying(20) NOT NULL,
    wf_desc character varying(100) NOT NULL,
    created_by character varying(30) NOT NULL,
    created_on timestamp without time zone NOT NULL
);


ALTER TABLE public.wf_master OWNER TO liquibase;

--
-- Name: wf_onboarding; Type: TABLE; Schema: public; Owner: liquibase
--

CREATE TABLE public.wf_onboarding (
    wf_id integer NOT NULL,
    mobile_number character varying(13) NOT NULL,
    wf_def_id integer NOT NULL,
    wf_stage_id integer NOT NULL,
    stage_status character varying(30) NOT NULL,
    reason character varying(100),
    created_by character varying NOT NULL,
    created_on timestamp without time zone NOT NULL
);


ALTER TABLE public.wf_onboarding OWNER TO liquibase;

--
-- Name: wf_onboarding_wf_id_seq; Type: SEQUENCE; Schema: public; Owner: liquibase
--

ALTER TABLE public.wf_onboarding ALTER COLUMN wf_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wf_onboarding_wf_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wf_stage_master; Type: TABLE; Schema: public; Owner: liquibase
--

CREATE TABLE public.wf_stage_master (
    wf_stage_id integer NOT NULL,
    wf_def_id integer NOT NULL,
    stage_name character varying(20) NOT NULL,
    stage_desc character varying(100) NOT NULL,
    order_stage integer NOT NULL,
    created_by character varying NOT NULL,
    created_on timestamp without time zone NOT NULL
);


ALTER TABLE public.wf_stage_master OWNER TO liquibase;

--
-- Name: workflow_stages; Type: TABLE; Schema: public; Owner: liquibase
--

CREATE TABLE public.workflow_stages (
    id uuid NOT NULL,
    onboarding_id uuid NOT NULL,
    workflow_stage character varying NOT NULL,
    stage_status character varying NOT NULL,
    remarks character varying NOT NULL,
    created timestamp without time zone NOT NULL
);


ALTER TABLE public.workflow_stages OWNER TO liquibase;

--
-- Name: workflows; Type: TABLE; Schema: public; Owner: liquibase
--

CREATE TABLE public.workflows (
    id uuid NOT NULL,
    device_id character varying(100) NOT NULL,
    device_details jsonb NOT NULL
);


ALTER TABLE public.workflows OWNER TO liquibase;

--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: liquibase
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
1	finx	src/main/resources/migrations.xml	2023-10-10 09:17:21.030888	1	EXECUTED	8:790f668d2c38c199cf924464e52268ce	createTable tableName=workflows		\N	4.15.0	\N	\N	6929440958
2	finx	src/main/resources/migrations.xml	2023-10-10 09:17:21.050337	2	EXECUTED	8:8a39ed34ec04dafbd19335dcfd27e5de	createTable tableName=workflow_stages		\N	4.15.0	\N	\N	6929440958
3	finx	src/main/resources/migrations.xml	2023-10-10 09:17:21.059939	3	EXECUTED	8:b2b0a0c73dffbf1d30538225d46bf345	createTable tableName=wf_master		\N	4.15.0	\N	\N	6929440958
4	finx	src/main/resources/migrations.xml	2023-10-10 09:17:21.073871	4	EXECUTED	8:5fe7ffbc03bb0ddae859aacd9448c4b6	createTable tableName=wf_stage_master		\N	4.15.0	\N	\N	6929440958
5	finx	src/main/resources/migrations.xml	2023-10-10 09:17:21.088584	5	EXECUTED	8:bb5cc8c6fabade4de5d8849c233cb061	createTable tableName=wf_onboarding		\N	4.15.0	\N	\N	6929440958
6	finx	src/main/resources/migrations.xml	2023-10-10 09:17:21.09542	6	EXECUTED	8:7983d55c8002a415a2cd750214dcf11a	sql		\N	4.15.0	\N	\N	6929440958
7	finx	src/main/resources/migrations.xml	2023-10-10 09:17:21.101657	7	EXECUTED	8:d1edcdd32060e53267d87000a942087c	sql		\N	4.15.0	\N	\N	6929440958
8	finx	src/main/resources/migrations.xml	2023-10-10 09:17:21.108871	8	EXECUTED	8:aa8acf1721045e51c7c80a89c3f5bfd3	sql		\N	4.15.0	\N	\N	6929440958
9	finx	src/main/resources/migrations.xml	2023-10-10 09:17:21.115489	9	EXECUTED	8:689f4f8ffdf46a77d2f9720c9e459d81	sql		\N	4.15.0	\N	\N	6929440958
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: liquibase
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: wf_master; Type: TABLE DATA; Schema: public; Owner: liquibase
--

COPY public.wf_master (wf_def_id, wf_name, wf_desc, created_by, created_on) FROM stdin;
101	Onboarding	To onboard a customer	Finx	2023-10-10 09:17:21.090709
\.


--
-- Data for Name: wf_onboarding; Type: TABLE DATA; Schema: public; Owner: liquibase
--

COPY public.wf_onboarding (wf_id, mobile_number, wf_def_id, wf_stage_id, stage_status, reason, created_by, created_on) FROM stdin;
\.


--
-- Data for Name: wf_stage_master; Type: TABLE DATA; Schema: public; Owner: liquibase
--

COPY public.wf_stage_master (wf_stage_id, wf_def_id, stage_name, stage_desc, order_stage, created_by, created_on) FROM stdin;
1	101	verify-mobile	Mobile verification stage	1	Finx	2023-10-10 09:17:21.097092
2	101	KYC	Know your customer stage	2	Finx	2023-10-10 09:17:21.103573
3	101	LIVE	Liveliness check stage	3	Finx	2023-10-10 09:17:21.110992
\.


--
-- Data for Name: workflow_stages; Type: TABLE DATA; Schema: public; Owner: liquibase
--

COPY public.workflow_stages (id, onboarding_id, workflow_stage, stage_status, remarks, created) FROM stdin;
\.


--
-- Data for Name: workflows; Type: TABLE DATA; Schema: public; Owner: liquibase
--

COPY public.workflows (id, device_id, device_details) FROM stdin;
\.


--
-- Name: wf_onboarding_wf_id_seq; Type: SEQUENCE SET; Schema: public; Owner: liquibase
--

SELECT pg_catalog.setval('public.wf_onboarding_wf_id_seq', 1, false);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: wf_master wf_master_pkey; Type: CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.wf_master
    ADD CONSTRAINT wf_master_pkey PRIMARY KEY (wf_def_id);


--
-- Name: wf_onboarding wf_onboarding_pkey; Type: CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.wf_onboarding
    ADD CONSTRAINT wf_onboarding_pkey PRIMARY KEY (wf_id);


--
-- Name: wf_stage_master wf_stage_master_pkey; Type: CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.wf_stage_master
    ADD CONSTRAINT wf_stage_master_pkey PRIMARY KEY (wf_stage_id);


--
-- Name: workflow_stages workflow_stages_pkey; Type: CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.workflow_stages
    ADD CONSTRAINT workflow_stages_pkey PRIMARY KEY (id);


--
-- Name: workflows workflows_pkey; Type: CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.workflows
    ADD CONSTRAINT workflows_pkey PRIMARY KEY (id);


--
-- Name: wf_onboarding fk_onboard_stage; Type: FK CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.wf_onboarding
    ADD CONSTRAINT fk_onboard_stage FOREIGN KEY (wf_stage_id) REFERENCES public.wf_stage_master(wf_stage_id);


--
-- Name: wf_stage_master fk_stage_workflow; Type: FK CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.wf_stage_master
    ADD CONSTRAINT fk_stage_workflow FOREIGN KEY (wf_def_id) REFERENCES public.wf_master(wf_def_id);


--
-- Name: workflow_stages fk_stages_workflows; Type: FK CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.workflow_stages
    ADD CONSTRAINT fk_stages_workflows FOREIGN KEY (onboarding_id) REFERENCES public.workflows(id);


--
-- Name: wf_onboarding fk_wf_onboarding; Type: FK CONSTRAINT; Schema: public; Owner: liquibase
--

ALTER TABLE ONLY public.wf_onboarding
    ADD CONSTRAINT fk_wf_onboarding FOREIGN KEY (wf_def_id) REFERENCES public.wf_master(wf_def_id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

